### ISSUE TITLE
I have issue with latest ga on static generation with react-static@2.5.6

### ISSUE THREAD

**Issue by JustFly1984** [react-ga/react-ga#320]
Have this error after update from 2.5.3 tp 2.5.6

```
 TypeError: Failed exporting HTML for URL 404 (src/pages/404.js): s.replace is not a function

  - react-ga.js:128 trim
    [drivemoscow-static]/[react-ga]/dist/react-ga.js:128:12

  - react-ga.js:367 Object.pageview
    [drivemoscow-static]/[react-ga]/dist/react-ga.js:367:32
```

**Comment by JustFly1984** [comment]
sorry, forgot to wrap the call in
```
if (typeof document !== 'undefined) {}
```
