### ISSUE TITLE
Issue in v2.5.0

### ISSUE THREAD

**Issue by CJ99** [react-ga/react-ga#246]
![error](https://user-images.githubusercontent.com/11033446/39141467-23c8568e-46e5-11e8-949c-ee854e275c67.png)

I got the error after upgraded to 2.5.0. 

I imported `import * as ReactGA from "react-ga";`. It worked in `2.4.1`, but not in `2.5.0`. Any idea?

**Comment by dsole** [comment]
The error looks to be caused by the same thing I'm seeing.
If so, I think we can change the issue title to be a bit more specific.

``
node_modules/react-ga/types/index.d.ts(8,8): error TS1192: Module '"/node_modules/@types/react/index"' has no default export.
``

In the recent release, `import React from 'react';` should be `import * as React from 'react';`

**Comment by dsole** [comment]
I've added a PR to fix that.

**Comment by entozoon** [comment]
Nice one @dsole 
In the meantime, a workaround that did it for me is popping this in your tsconfig.json
